set UTF_SYMBOLS_DB(UTF__ZCUI_CWD) /home/grads/s/sujaysimha/CSCE_689/lab-4-SujaySimha81/zebu 
set UTF__GENERATED_CMDS [list]
set UTF_SYMBOLS_DB(FETCH_MODE_ENABLED) -1 
set UTF_SYMBOLS_DB(ZEMI3_FM_OPT_ENABLED) -1 
