cluster_generated -part_name Part_0 -lut 2666 -bram 1726 -reg 72 -dsp 8 -ramlut 194 -cut 0
defcoremapping {top.assert_design_req1_empty_assert} Part_0
defcoremapping {top.assert_design_req1_empty_assert_sva_enable} Part_0
defcoremapping {top.assert_design_req2_full_assert} Part_0
defcoremapping {top.assert_design_req2_full_assert_sva_enable} Part_0
defcoremapping {top.ended_toggle_assert_design_req1_empty_assert} Part_0
defcoremapping {top.ended_toggle_assert_design_req2_full_assert} Part_0
defcoremapping {top.inv90} Part_0
defcoremapping {top.inv91} Part_0
defcoremapping {top.u_dut} Part_0
defcoremapping {top.u_stb} Part_0
defcoremapping {top.val} Part_0
defcoremapping {top.zafth__I_vcs_cdx_s_rw_topu_stb_clk0} Part_0
defcoremapping {top.zafth__I_vcs_cdx_s_rw_topu_stb_clk1} Part_0
defcoremapping {top.zebu_FT_inout_mod_hidden_wire_new} Part_0
defcoremapping {top.zebu_clockGen} Part_0
defcoremapping {top.zfast_13dazc5xo4v01} Part_0
defcoremapping {top.zfast_9bva7lnd5m8p} Part_0
defcoremapping {top.zfast_fghdd7qi7m56} Part_0
defcoremapping {top.zfast_nes3tozxfg5o2} Part_0
defcoremapping {top.zfast_ttitjas49lqq1} Part_0
defcoremapping {top.zfast_zew6gorl0sct} Part_0
defcoremapping {top.zforce_rstn} Part_0
defcoremapping {top.zfwc_ip__I_vcs_cdx_s_rw_topu_stb_clk0} Part_0
defcoremapping {top.zfwc_ip__I_vcs_cdx_s_rw_topu_stb_clk0_0} Part_0
defcoremapping {top.zfwc_ip__I_vcs_cdx_s_rw_topu_stb_clk1} Part_0
defcoremapping {top.zfwc_ip__I_vcs_cdx_s_rw_topu_stb_clk1_0} Part_0
defcoremapping {top.zfwc_ip_monitor} Part_0
defcoremapping {top.zfwc_ip_monitor_0} Part_0
defcoremapping {top.zsva_trigger_assert_design_req1_empty_assert} Part_0
defcoremapping {top.zsva_trigger_assert_design_req2_full_assert} Part_0
